/*
 The database contains the following tables:
 Customers: Contains information about the customers, such as customer ID, name, email, and location.
 Orders: Contains information about the orders placed by customers, such as order ID, customer ID, order date, and total amount.
 Products: Contains information about the products available for purchase, such as product ID, name, description, and price.
 Categories: Contains information about the different categories of products, such as category ID and name.
 Order_Items: Contains information about the individual items included in each order, such as order item ID, order ID, product ID, quantity, and unit price.
 
 taskThree : Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.
 */

SELECT
    c.name AS product_category_name,
    SUM(p.price * oi.quantity) AS total_revenue
FROM Categories c
    JOIN Products p ON c.category_id = p.category_id
    JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.name
ORDER BY total_revenue DESC;